### PR TITLE
Fix codeaurora URL.

### PR DESCRIPTION
**Pull request by ghost**
Avoiding this error:
fatal: unable to connect to codeaurora.org:

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Syncs fine here..

**Comment by TheCrazyLex** [comment]
(without this patch)

**Comment by ghost** [comment]
I've got many of this errors then I've found [this]( https://wiki.codeaurora.org/xwiki/bin/Support/caf_faq#HBenefitsofafullreposyncvs.gitcloneofarepo) recommendation and got work now. 
I have a proxy and other network things at way, so perhaps that's why I got errors.

**Comment by TheCrazyLex** [comment]
Yeah, we tried doing this changed once already, however then a lot of other people had sync issues, so we cannot accept this globally

**Pull request closed without merging**
