### PR TITLE
Merge tag 'android-6.0.1_r55' into marshmallow-caf

### PR DESCRIPTION
**Pull request by Herna1994**
Android 6.0.1 Release 55 (MXC89K)

### CODE REVIEW

**Comment by SferaDev** [comment]
We have r54 already merged on private git, we will mirror July patches to github once a new build is released.

**Comment by TheCrazyLex** [comment]
@SferaDev No, he is right. CAF didn't merge it yet. We plan to use @Herna1994 's merge :)

**Comment by SferaDev** [comment]
Wait I misread branch names, nevermind!

**Comment by evan-a-a** [comment]
We want r54 though, not r55. r54 aligns with Nexus

**Comment by Herna1994** [comment]
I think it's easier to you to update to r55 from r54 than me to do the
reverse.

Anyway if it's extremely required I will go back to r54, but differences
are minimal/inexistent.

**Comment by evan-a-a** [comment]
If I'm not mistaken, r55 and r54 are separate branches and that causes problems. Nexus is tracking with the MTC series of releases.

**Comment by evan-a-a** [comment]
Indeed, MXC89K  is a separate branch and is designated for Pixel C only

https://groups.google.com/d/msg/android-building/31YK54N_SJo/pfjYqyxfDAAJ

**Comment by Herna1994** [comment]
My fault so, didn't check groups.google release thread.

Will have r54 uploaded by this afternoon(GMT+1).

**Comment by SferaDev** [comment]
@Herna1994 We've already set up gerrit, check if you can work over there this afternoon.

**Comment by SferaDev** [comment]
Giving it second thoughts it could be messy to upload all changes there... PR them here for now and we'll bypass gerrit replication instead of merging the PR.

**Comment by Herna1994** [comment]
Better better, I will give Jake links to the repos updated so he only has
to bypass those merges via gerrit.

Will leave a message when it's done.

Saludos xD

**Pull request closed without merging**
