### PR TITLE
Uber

### PR DESCRIPTION
**Pull request by EyeCantCU**
In my experience, Uber has proved to be more efficient when it comes to battery life and a bit better performance wise. I also tracked GCC 5.x as pretty soon it will most likely become the new standard unless the transition to Clang is closer than I thought (DTC may be something we should track in the future as well).

If anyone wants quantitative results for comparison, I can do that, but it may take me a couple of days to get around to it.

Thanks everyone.

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Get me these results please haha 
Also AOSP won't switch to 5.0, so we want to stay at 4.9

Alex

**Comment by EyeCantCU** [comment]
@TheCrazyLex I'll do that. I'll go ahead and close this for now and open a new one with just 4.9 afterwards

**Comment by dvandenburgh** [comment]
#buzzwords

**Comment by TheCrazyLex** [comment]
@Seraph08 ^^

**Pull request closed without merging**
